import type { CandidateKind, EvidenceStrength, LearningCandidate, LearningEvaluation, LearningEvidence, PolicyOverlay, TaskSignature } from '@aes/spec';
import type { LearningArtifactStore, RuntimeDecisionTrace, RuntimeLearningObserver, RuntimeObservationSink } from '@aes/runtime-sdk';
import { ExperienceMiner, LearningEvaluationEngine, matchesApplicability, PolicyOverlayEngine, RegressionMonitor, ShadowEvaluator } from '@aes/kernel';
import { toLearningEvidence } from './experience-adapter.js';

const RANK: Record<EvidenceStrength, number> = { observational: 0, comparative: 1, controlled: 2 };
const AUTO = new Set<CandidateKind>(['model_preference', 'latency_preference', 'context_preference', 'retry_preference', 'replan_preference', 'interruption_preference']);

export interface LearningEvidenceStore { append(evidence: LearningEvidence): Promise<void>; query(signature: TaskSignature): Promise<LearningEvidence[]>; }
export interface AdaptiveLearningCoordinatorOptions {
  signatureForTrace: (trace: RuntimeDecisionTrace) => TaskSignature; miner: ExperienceMiner; evaluator: LearningEvaluationEngine; overlays: PolicyOverlayEngine; regression: RegressionMonitor; regressionAvailable?: () => boolean; shadow: ShadowEvaluator; artifacts: LearningArtifactStore; evidenceStore: LearningEvidenceStore; observations?: RuntimeObservationSink; maintenance?: { incremental(): Promise<void>; full(): Promise<void>; fullCompileAfterNewTraces: number }; autoActivation?: { enabled: boolean; requireShadow: boolean; minimumEvidenceStrengthByKind: Partial<Record<CandidateKind, EvidenceStrength>> }; analysisBudget?: { maxCandidatesPerTask: number; maxIncrementalWorkMs: number }; now: () => string; nowMs: () => number;
}

export class AdaptiveLearningCoordinator implements RuntimeLearningObserver {
  #newTraceCount = 0;
  constructor(private readonly deps: AdaptiveLearningCoordinatorOptions) {}
  async observe(trace: RuntimeDecisionTrace): Promise<void> {
    const started = this.deps.nowMs(); const signature = this.deps.signatureForTrace(trace); const evidence = toLearningEvidence(trace, signature); await this.deps.evidenceStore.append(evidence); this.deps.observations?.emit({ type: 'learning.evidence.accepted', evidenceId: evidence.id, scope: 'project' });
    const comparable = await this.deps.evidenceStore.query(signature); const candidates = this.deps.miner.mineModelPreference(comparable, 'project', this.deps.now()).sort((a, b) => a.id.localeCompare(b.id)).slice(0, this.deps.analysisBudget?.maxCandidatesPerTask ?? 3);
    for (const candidate of candidates) { if (!this.within(started)) break; await this.process(candidate, trace, comparable); }
    await this.monitor(signature); if (this.deps.maintenance && this.within(started)) { this.#newTraceCount += 1; await this.deps.maintenance.incremental(); if (this.#newTraceCount >= this.deps.maintenance.fullCompileAfterNewTraces) { await this.deps.maintenance.full(); this.#newTraceCount = 0; } }
  }
  private within(started: number) { return this.deps.nowMs() - started <= (this.deps.analysisBudget?.maxIncrementalWorkMs ?? 500); }
  private async process(candidate: LearningCandidate, trace: RuntimeDecisionTrace, evidence: readonly LearningEvidence[]) { const old = (await this.deps.artifacts.listCandidates()).find((item) => item.id === candidate.id); if (old && ['active', 'degraded', 'disabled', 'superseded'].includes(old.status)) return; await this.deps.artifacts.putCandidate(candidate); if (!old) this.deps.observations?.emit({ type: 'learning.candidate.created', candidateId: candidate.id, kind: candidate.kind, scope: candidate.scope }); const shadowCandidate = { ...candidate, status: 'shadow' as const, updatedAt: this.deps.now() }; await this.deps.artifacts.putCandidate(shadowCandidate); let recorded = false; if (candidate.effect?.kind === 'model_preference') { const baseline = trace.resolution.selected.traits.qualityClass; const shadow = this.deps.shadow.record({ candidateId: candidate.id, baselineDecision: { modelClass: baseline }, shadowDecision: { modelClass: candidate.effect.prefer }, comparable: baseline === candidate.effect.prefer, ...(baseline === candidate.effect.prefer ? { observedOutcome: trace.telemetry.verification } : {}), timestamp: this.deps.now() }); await this.deps.artifacts.putShadowDecision(shadow); this.deps.observations?.emit({ type: 'learning.candidate.shadowed', candidateId: candidate.id }); recorded = true; } await this.evaluate(shadowCandidate, evidence, recorded); }
  private async evaluate(candidate: LearningCandidate, evidence: readonly LearningEvidence[], shadowRecorded: boolean) { const rows = evidence.filter((row) => matchesApplicability(row.signature, candidate.applicability)); const groups = this.deps.miner.aggregateModelChoices(rows); const selected = groups.find((group) => candidate.effect?.kind === 'model_preference' && group.choice === candidate.effect.prefer); const baseline = groups.filter((group) => group.choice !== selected?.choice).sort((a, b) => b.metrics.verifiedSuccessRate - a.metrics.verifiedSuccessRate || a.choice.localeCompare(b.choice))[0]; if (!selected || !baseline) return; const evaluation = this.deps.evaluator.evaluate({ candidate, candidateMetrics: selected.metrics, baselineMetrics: baseline.metrics, stableWindows: this.deps.miner.stablePreferenceWindows(rows, selected.choice), evaluatedAt: this.deps.now() }); await this.deps.artifacts.putEvaluation(evaluation); this.deps.observations?.emit({ type: 'learning.evaluation.completed', candidateId: candidate.id, outcome: evaluation.outcome }); if (evaluation.outcome !== 'validate') { await this.deps.artifacts.putCandidate({ ...candidate, status: evaluation.outcome === 'reject' ? 'rejected' : candidate.status, evaluationRefs: [...new Set([...candidate.evaluationRefs, evaluation.id])].sort(), updatedAt: this.deps.now() }); return; } const validated = { ...candidate, status: 'validated' as const, evaluationRefs: [...new Set([...candidate.evaluationRefs, evaluation.id])].sort(), updatedAt: this.deps.now() }; await this.deps.artifacts.putCandidate(validated); const minimum = this.deps.autoActivation?.minimumEvidenceStrengthByKind[candidate.kind] ?? 'controlled'; if (!(this.deps.autoActivation?.enabled && (this.deps.regressionAvailable?.() ?? true) && candidate.scope === 'project' && AUTO.has(candidate.kind) && candidate.effect && (!this.deps.autoActivation.requireShadow || shadowRecorded) && RANK[candidate.evidenceStrength] >= RANK[minimum])) return; const overlay: PolicyOverlay = { id: `overlay:${candidate.id}`, sourceCandidateId: candidate.id, scope: 'project', status: 'active', applicability: candidate.applicability, effect: candidate.effect, evidenceRefs: [...candidate.evidenceRefs], evaluationRefs: [...validated.evaluationRefs], evidenceStrength: candidate.evidenceStrength, evaluationScore: 4, baseline: { verifiedRate: baseline.metrics.verifiedSuccessRate, retryRate: baseline.metrics.retryRate, interruptionRate: baseline.metrics.interruptionRate, ...(baseline.metrics.averageEstimatedCost ? { averageCost: baseline.metrics.averageEstimatedCost } : {}) }, createdAt: this.deps.now(), updatedAt: this.deps.now() }; await this.deps.artifacts.putOverlay(overlay); await this.deps.artifacts.putCandidate({ ...validated, status: 'active', updatedAt: this.deps.now() }); this.deps.observations?.emit({ type: 'learning.overlay.activated', overlayId: overlay.id, scope: 'project' }); }
  private async monitor(signature: TaskSignature) { const overlays = (await this.deps.artifacts.listOverlays()).filter((overlay) => overlay.status === 'active' && overlay.baseline && matchesApplicability(signature, overlay.applicability)); const evidence = await this.deps.evidenceStore.query(signature); for (const overlay of overlays) { const result = this.deps.regression.evaluate({ baseline: overlay.baseline!, observed: evidence.filter((row) => row.timestamp > overlay.createdAt), overlayId: overlay.id }); if (result.action !== 'degrade') continue; await this.deps.artifacts.putOverlay({ ...overlay, status: 'degraded', updatedAt: this.deps.now() }); const source = (await this.deps.artifacts.listCandidates()).find((candidate) => candidate.id === overlay.sourceCandidateId); if (source) await this.deps.artifacts.putCandidate({ ...source, status: 'degraded', updatedAt: this.deps.now() }); this.deps.observations?.emit({ type: 'learning.overlay.degraded', overlayId: overlay.id, reason: result.reason }); } }
  async listActiveOverlays() { return (await this.deps.artifacts.listOverlays()).filter((overlay) => overlay.status === 'active'); }
  async disableOverlay(id: string, now: string) { const overlay = (await this.deps.artifacts.listOverlays()).find((item) => item.id === id); if (!overlay) throw new Error(`unknown overlay ${id}`); await this.deps.artifacts.putOverlay({ ...overlay, status: 'disabled', updatedAt: now }); const source = (await this.deps.artifacts.listCandidates()).find((item) => item.id === overlay.sourceCandidateId); if (source) await this.deps.artifacts.putCandidate({ ...source, status: 'disabled', updatedAt: now }); this.deps.observations?.emit({ type: 'learning.overlay.disabled', overlayId: id, reason: 'explicit disable' }); }
  async explainOverlay(id: string) { const overlay = (await this.deps.artifacts.listOverlays()).find((item) => item.id === id); return overlay ? { overlayId: overlay.id, sourceCandidateId: overlay.sourceCandidateId, evidenceStrength: overlay.evidenceStrength, evidenceRefs: [...overlay.evidenceRefs], evaluationRefs: [...overlay.evaluationRefs], baseline: overlay.baseline } : undefined; }
}
