import type { KnowledgeRecord } from '@aes/spec';
export type MemoryLintCode = 'duplicate' | 'conflict' | 'orphan_relation' | 'missing_provenance' | 'low_evidence_active' | 'oversized_record' | 'scope_risk' | 'active_record_budget' | 'index_budget' | 'stale_active';
export interface MemoryLintFinding { code: MemoryLintCode; recordIds: string[]; repairable: boolean; message: string; }
export interface MemoryLintBudget { maxActiveRecords: number; maxRecordTokens: number; maxIndexTokens: number; }
export class MemoryLint {
  inspect(input: { records: readonly KnowledgeRecord[]; budget: MemoryLintBudget; renderedIndex: string; staleBefore?: string }): MemoryLintFinding[] {
    const ids = new Set(input.records.map((record) => record.id)); const findings: MemoryLintFinding[] = [];
    for (const record of input.records) { if (!record.provenance.refs.length) findings.push({ code: 'missing_provenance', recordIds: [record.id], repairable: false, message: 'durable record has no provenance refs' }); if (record.status === 'active' && !record.evidenceRefs.length) findings.push({ code: 'low_evidence_active', recordIds: [record.id], repairable: false, message: 'active learned record has no evidence refs' }); if (Math.ceil(record.statement.length / 4) > input.budget.maxRecordTokens) findings.push({ code: 'oversized_record', recordIds: [record.id], repairable: false, message: 'record exceeds token budget' }); for (const relation of record.relations) if (!ids.has(relation.targetId)) findings.push({ code: 'orphan_relation', recordIds: [record.id], repairable: false, message: `missing relation target ${relation.targetId}` }); if (input.staleBefore && record.status === 'active' && record.updatedAt < input.staleBefore) findings.push({ code: 'stale_active', recordIds: [record.id], repairable: false, message: 'active record requires evidence review' }); }
    const active = input.records.filter((record) => record.status === 'active'); if (active.length > input.budget.maxActiveRecords) findings.push({ code: 'active_record_budget', recordIds: active.map((record) => record.id).sort(), repairable: false, message: `active knowledge count ${active.length} exceeds ${input.budget.maxActiveRecords}` }); if (Math.ceil(input.renderedIndex.length / 4) > input.budget.maxIndexTokens) findings.push({ code: 'index_budget', recordIds: [], repairable: true, message: `derived index exceeds ${input.budget.maxIndexTokens} estimated tokens` }); return findings.sort((a, b) => a.code.localeCompare(b.code) || a.recordIds.join(':').localeCompare(b.recordIds.join(':')));
  }
}
